export const ErrorCode = {
	UNKNOWN_ERROR: "UNKNOWN_ERROR",
	INTERNAL_ERROR: "INTERNAL_ERROR",
	NETWORK_ERROR: "NETWORK_ERROR",
	RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

	EXPIRED_TOKEN: "EXPIRED_TOKEN",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	MISSING_REFRESH_TOKEN: "MISSING_REFRESH_TOKEN",
	UNAUTHORIZED: "UNAUTHORIZED",

	INVALID_REQUEST: "INVALID_REQUEST",
	INVALID_TYPE: "INVALID_TYPE",
	MISSING_FIELDS: "MISSING_FIELDS",

	VALUE_EXISTS: "VALUE_EXISTS",
	INVALID_TOO_SHORT: "INVALID_TOO_SHORT",
	INVALID_TOO_LONG: "INVALID_TOO_LONG",
	INVALID_EMAIL: "INVALID_EMAIL",
	INVALID_ICON: "INVALID_ICON",
	TOO_LARGE: "TOO_LARGE",

	INVALID_GAME_CODE: "INVALID_GAME_CODE",
	GAME_NOT_CREATED: "GAME_NOT_CREATED",
	GAME_NOT_FOUND: "GAME_NOT_FOUND",
	PLAYER_NOT_IN_LOBBY: "PLAYER_NOT_IN_LOBBY",
	ALREADY_IN_GAME: "ALREADY_IN_GAME",
	GAME_FULL: "GAME_FULL",
	GAME_NOT_IN_LOBBY: "GAME_NOT_IN_LOBBY",
	GAME_ALREADY_STARTED: "GAME_ALREADY_STARTED",
	INVALID_SEAT: "INVALID_SEAT",
	SEAT_TAKEN: "SEAT_TAKEN",
	NOT_GAME_LEADER: "NOT_GAME_LEADER",
	LOBBY_TOO_SMALL: "LOBBY_TOO_SMALL",
	BOT_NOT_ADDED: "BOT_NOT_ADDED",
	INVALID_ACTION: "INVALID_ACTION",
	PLAYER_ELIMINATED: "PLAYER_ELIMINATED",
	CHAT_NOT_ALLOWED: "CHAT_NOT_ALLOWED",

	USER_NOT_FOUND: "USER_NOT_FOUND",
	FRIENDSHIP_ALREADY_EXISTS: "FRIENDSHIP_ALREADY_EXISTS",
	FRIENDSHIP_ALREADY_SENT: "FRIENDSHIP_ALREADY_SENT",
	FRIEND_REQUEST_EXISTS: "FRIEND_REQUEST_EXISTS",
	USER_NOT_FRIEND: "USER_NOT_FRIEND",
	USER_BLOCKED: "USER_BLOCKED",
	FRIENDSHIP_NOT_FOUND: "FRIENDSHIP_NOT_FOUND",
	FRIENDS_LIMIT_REACHED: "FRIENDS_LIMIT_REACHED",
	FRIEND_REQUEST_OUTGOING_LIMIT_REACHED: "FRIEND_REQUEST_OUTGOING_LIMIT_REACHED",
	FRIEND_REQUEST_INCOMING_LIMIT_REACHED: "FRIEND_REQUEST_INCOMING_LIMIT_REACHED",
	TOO_SOON: "TOO_SOON",
} as const

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode]

export type ApiResponse<T = unknown> =
	| { success: true; result?: T }
	| { success: false; errors: ErrorDetail[] }

export type ErrorDetail = {
	code: ErrorCodeType
	field?: string
}

export class AppError extends Error {
	public readonly code: ErrorCodeType
	public readonly details?: ErrorDetail[]

	constructor(code: ErrorCodeType, details?: ErrorDetail[]) {
		super(code)
		this.name = "AppError"
		this.code = code
		this.details = details
	}
}

export type Pagination = {
	offset: number
	limit: number
}

export type PaginatedResult<T> = {
	data: T[]
	total: number
	offset: number
	limit: number
}
